"""Servicio de inferencia y validación que alimenta la demo Streamlit del proyecto."""

from src.inference.app_service import (
    APP_MODEL_PATH_ENV,
    AppInferenceError,
    BatchResult,
    FeatureInputSpec,
    ModelBundle,
    SinglePrediction,
    build_single_record_frame,
    build_template_frame,
    feature_input_specs,
    load_app_model,
    normalize_uploaded_frame,
    order_prediction_columns,
    predict_single,
    predictions_to_csv_bytes,
    read_uploaded_table,
    resolve_app_model_path,
    run_batch_prediction,
    template_csv_bytes,
)
from src.inference.batch_validation import (
    MAX_BATCH_ROWS,
    ValidationIssue,
    ValidationReport,
    clinical_ranges,
    coerce_feature_types,
    valid_gender_values,
    validate_batch_features,
)

__all__ = [
    "APP_MODEL_PATH_ENV",
    "MAX_BATCH_ROWS",
    "AppInferenceError",
    "BatchResult",
    "FeatureInputSpec",
    "ModelBundle",
    "SinglePrediction",
    "ValidationIssue",
    "ValidationReport",
    "build_single_record_frame",
    "build_template_frame",
    "clinical_ranges",
    "coerce_feature_types",
    "feature_input_specs",
    "load_app_model",
    "normalize_uploaded_frame",
    "order_prediction_columns",
    "predict_single",
    "predictions_to_csv_bytes",
    "read_uploaded_table",
    "resolve_app_model_path",
    "run_batch_prediction",
    "template_csv_bytes",
    "valid_gender_values",
    "validate_batch_features",
]
